Photo upload
johnnyvuanly/lmn pull request #22
Opened 2021-05-04 18:48 UTC by ajgoranson

A few issues tackled with this and tests. We can go over the code on Wednesday and make sure it is all good

2021-05-06 20:32 UTC, ajgoranson commented
@claraj Could you please review this code? It's for photo upload and updating and deleting a note with unittests!

2021-05-06 21:01 UTC, claraj requested changes
This looks like it has changes related to deleting notes too. Assuming no-one else has worked on this and the code is working, I'd leave it in.  

Remove the example image files used.

I tried to run the code and it's crashing since Pillow is not listed in requirements.txt.

Have you got a test to check if a user can edit their own note?
And a test to make sure a user CANT edit someone else's note? 

Thanks!

2021-05-06 21:11 UTC, ajgoranson commented on lmn/tests/test_views.py
> +from os import terminal_size
OS was needed others not

2021-05-06 21:14 UTC, ajgoranson commented on lmn/templates/lmn/users/user_profile.html
> +{% if messages %}
Yes because you get reverted to the user profile page with a message that comes up after deleting

2021-05-06 21:17 UTC, ajgoranson commented on lmn/views/views_notes.py
> +        messages.info(request, 'Unable to delete')
Changed to return HTTP response and a redirect

2021-05-06 21:21 UTC, ajgoranson commented
@claraj could you do a final review? i fixed the issues that you previously stated

2021-05-06 21:34 UTC, claraj requested changes
Looks good. You need tests for editing notes - can you edit your own note? Can I edit your note? Hopefully not :)

2021-05-06 21:34 UTC, claraj commented on lmn/tests/test_views.py
> +class TestDeletePlace(TestCase):
Place?

2021-05-06 21:34 UTC, claraj commented on lmn/tests/test_views.py
> +from django.test import override_settings
Is this used?

2021-05-06 21:34 UTC, claraj commented on lmn/tests/test_views.py
> +
Blank line needed

2021-05-06 21:43 UTC, ajgoranson commented on lmn/tests/test_views.py
> +from django.test import override_settings
Image is used override was not

2021-05-06 21:48 UTC, ajgoranson commented
I have tests that have todo with editing notes on line 564 and 594, they were misnamed so I renamed them

2021-05-06 21:50 UTC, ajgoranson commented
@claraj  See above comment forgot to tag you

2021-05-07 01:09 UTC, johnnyvuanly commented
Do the jpg files need to be uploaded to GItHub? @ajgoranson

2021-05-07 01:25 UTC, claraj commented on lmn/tests/test_views.py
> +    def test_deleting_somebodys_note_that_is_not_yours_doesnt_work(self):
this is an excellent test name

2021-05-07 01:28 UTC, claraj commented
> I have tests that have todo with editing notes on line 564 and 594, they were misnamed so I renamed them

These are for editing the image for a note  - that's an important thing to test. How about editing text or title for a note?

2021-05-10 18:51 UTC, johnnyvuanly commented
Aaron showed me user is able to edit and delete their own notes. They cannot edit another users notes. Users are able to upload an image on a new note and can go back and edit a note to include a image. Lastly user can share notes to social media, specifically twitter and facebook using the social-share-django library that is now included in the requirements.txt. We noticed a bug where single quotes show up as "&#x27:t" when user tries to share to social media. In any case the feature works still.

2021-05-10 18:52 UTC, johnnyvuanly commented
Aaron also showed me all the passing tests that he did for the notes edit, the photo upload and the social media integration.

2021-05-10 18:52 UTC, merged