Google Cloud deployment
johnnyvuanly/lmn pull request #23
Opened 2021-05-06 04:52 UTC by 4LineTime

settings.py is where the fun stuff is, and it is very minimal. As I'm sure you know, most of the action is in the command line and the google cloud web interface. 
Our url is here:
https://clear-booking-309320.uc.r.appspot.com/

Please break it if you can.

This branch also happens to add a ton of files in the static folder. I'm not sure if that is where they are supposed to be. I followed Clara's slides and there they are. These are direct copies of files elsewhere.

2021-05-06 21:03 UTC, claraj commented
> 
> This branch also happens to add a ton of files in the static folder. I'm not sure if that is where they are supposed to be. I followed Clara's slides and there they are. These are direct copies of files elsewhere.

That's completely fine. You work on the originals, and then collectstatic gathers them all up and copies into the static folder, and those files are used for the live site.

2021-05-07 00:57 UTC, johnnyvuanly commented
I see that the app is deployed successfully at GCP! Great work Orion. I'm guessing all of these files added were from GCP?

2021-05-11 12:56 UTC, claraj requested changes

2021-05-11 12:56 UTC, claraj commented on .gitignore
> +requirements.txt
I don't think you should ignore this. both github and GCP need this file

2021-05-11 12:56 UTC, claraj commented on .gitignore
>  cloud_sql_proxy_x64.exe
There's some duplicates here, remove extra cloud_sql_proxy_x64.exe

2021-05-12 02:43 UTC, ajgoranson commented
Tested and used all the application features, it is working great!

2021-05-12 02:43 UTC, merged